{
 "title": "Solar monitor",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Power",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "W/VA" }
   ],
   "targets": [
    {
     "alias": "AC output (VA)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_status",
     "select": [
      [
       { "params": [ "ac_output_va" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test_installation1" }
     ]
    },
    {
     "alias": "AC output (W)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_status",
     "select": [
      [
       { "params": [ "ac_output_w" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test_installation1" }
     ]
    },
    {
     "alias": "AC rating (VA)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_rating",
     "select": [
      [
       { "params": [ "ac_output_va" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test_installation1" }
     ]
    },
    {
     "alias": "AC rating (W)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_rating",
     "select": [
      [
       { "params": [ "ac_output_w" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test_installation1" }
     ]
    }
   ]
  },
  {
   "title": "Battery capacity",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 12, "y": 0 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_status",
     "query": "SELECT last(\"battery_capacity\") FROM \"system_status\" WHERE (\"host\" = 'test_installation1')",
     "select": [
      [
       { "params": [ "battery_capacity" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test_installation1" }
     ]
    }
   ]
  },
  {
   "title": "Inverter temperature",
   "type": "singlestat",
   "gridPos": { "h": 5, "w": 3, "x": 15, "y": 0 },
   "format": "celsius",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_status",
     "select": [
      [
       { "params": [ "inverter_temperature" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test_installation1" }
     ]
    }
   ]
  },
  {
   "title": "Battery re-discharge",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 0 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_rating",
     "select": [
      [
       { "params": [ "battery_redischarge_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test_installation1" }
     ]
    }
   ]
  },
  {
   "title": "Battery recharge",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 0 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_rating",
     "select": [
      [
       { "params": [ "battery_recharge_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test_installation1" }
     ]
    }
   ]
  },
  {
   "title": "Battery rating",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 18, "y": 2 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_rating",
     "select": [
      [
       { "params": [ "battery_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test_installation1" }
     ]
    }
   ]
  },
  {
   "title": "Battery rating",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 3, "x": 21, "y": 2 },
   "format": "volt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_rating",
     "select": [
      [
       { "params": [ "battery_under_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test_installation1" }
     ]
    }
   ]
  },
  { "title": "Alerts", "type": "alertlist", "gridPos": { "h": 7, "w": 6, "x": 18, "y": 4 } },
  {
   "title": "Charging",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_status",
     "select": [
      [
       { "params": [ "charging_on" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test_installation1" }
     ]
    }
   ]
  },
  {
   "title": "SSC charging",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 5 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_status",
     "select": [
      [
       { "params": [ "scc_charging_on" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test_installation1" }
     ]
    }
   ]
  },
  {
   "title": "Max AC charge",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 5 },
   "format": "amp",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_rating",
     "select": [
      [
       { "params": [ "max_ac_charge_current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test_installation1" }
     ]
    }
   ]
  },
  {
   "title": "AC Charging",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 12, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_status",
     "select": [
      [
       { "params": [ "ac_charging_on" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test_installation1" }
     ]
    }
   ]
  },
  {
   "title": "Load status",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 14, "y": 8 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_status",
     "select": [
      [
       { "params": [ "load_status" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test_installation1" }
     ]
    }
   ]
  },
  {
   "title": "Max  charge",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 2, "x": 16, "y": 8 },
   "format": "amp",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_rating",
     "select": [
      [
       { "params": [ "max_charge_current" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test_installation1" }
     ]
    }
   ]
  },
  {
   "title": "Voltages",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Volt" }
   ],
   "targets": [
    {
     "alias": "Grid",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_status",
     "query": "SELECT mean(\"grid_voltage\") FROM \"system_status\" WHERE (\"host\" = 'test_installation1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "grid_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test_installation1" }
     ]
    },
    {
     "alias": "AC Output",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_status",
     "select": [
      [
       { "params": [ "ac_output_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test_installation1" }
     ]
    },
    {
     "alias": "Battery Recharge",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_status",
     "query": "SELECT max(\"battery_recharge_voltage\") FROM \"system_status\" WHERE (\"host\" = 'test_installation1') AND $timeFilter GROUP BY time($__interval) fill(null)",
     "select": [
      [
       { "params": [ "battery_recharge_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test_installation1" }
     ]
    },
    {
     "alias": "Battery Bulk",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_status",
     "select": [
      [
       { "params": [ "battery_bulk_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test_installation1" }
     ]
    },
    {
     "alias": "Battery",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_status",
     "select": [
      [
       { "params": [ "battery_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test_installation1" }
     ]
    },
    {
     "alias": "PV input voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_status",
     "select": [
      [
       { "params": [ "pv_input_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test_installation1" }
     ]
    },
    {
     "alias": "SCC battery voltage",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_status",
     "select": [
      [
       { "params": [ "scc_battery_voltage" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test_installation1" }
     ]
    }
   ]
  },
  {
   "title": "Charger source priority",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 11 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_rating",
     "select": [
      [
       { "params": [ "charger_source_priority" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test_installation1" }
     ]
    }
   ]
  },
  {
   "title": "Output source priority",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 12, "y": 13 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "system_rating",
     "select": [
      [
       { "params": [ "output_source_priority" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "host", "operator": "=", "value": "test_installation1" }
     ]
    }
   ]
  }
 ]
}